language: php
php:
  - 7.3

matrix:
  fast_finish: true

install:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - composer phpstan
  - composer phpcs
  - composer tests
